name: Package and release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -w 26550 -p 826042         
